<div style="max-width:900px;margin:0 auto"><h1>Import Questions from JSON</h1><p style="color:var(--text-muted)">Validate a JSON file, review its preview, then import it into one selected module subject.</p>
<?php if($errors):?><div class="alert alert-error"><?php foreach($errors as $error):?><div><?=e($error)?></div><?php endforeach;?></div><?php endif;?>
<?php if($result):?><div class="alert alert-success">Created <?= (int)$result['new_questions']?> question(s), added <?= (int)$result['added_appearances']?> appearance(s), skipped <?= (int)$result['duplicate_appearances']?> duplicate appearance(s)<?php if(($result['conflicts']??0)>0):?>, and recorded <?= (int)$result['conflicts']?> answer conflict(s) for review<?php endif;?>. <a href="<?=url('admin/questions.php')?>">Open Question Bank</a></div><?php endif;?>
<?php if($preview):?><div class="card"><h2>Import Preview</h2><p>Target: <?=e($preview['module'])?> → <?=e($preview['subject'])?></p><h3>What will happen</h3><ul><li>Total records: <?= (int)$preview['summary']['total']?></li><li>Valid records to process: <?= (int)$preview['summary']['valid']?></li><li>Invalid records not imported: <?= (int)$preview['summary']['invalid']?></li><li>New question rows: <?= (int)($preview['summary']['new_questions']??0)?></li><li>Records reusing or merging with existing questions: <?= (int)($preview['summary']['merge_records']??0)?></li><li>Duplicate appearances skipped: <?= (int)($preview['summary']['duplicate_appearances']??0)?></li><li>Review warnings: <?= (int)($preview['summary']['warning_count']??count($preview['warnings']))?></li></ul><p>With answers: <?= (int)$preview['summary']['with_answers']?> · Without answers: <?= (int)$preview['summary']['without_answers']?></p>
<?php if($preview['warnings']):?><h3>Review warnings</h3><ul><?php foreach($preview['warnings'] as $item):?><li>Question <?= (int)$item['number']?>: <?=e(implode(' ',$item['warnings']))?></li><?php endforeach;?></ul><?php endif;?>
<?php if($preview['invalid']):?><h3>Invalid records</h3><ul><?php foreach($preview['invalid'] as $item):?><li>Question <?= (int)$item['number']?>: <?=e(implode(' ',$item['errors']))?></li><?php endforeach;?></ul><?php endif;?>
<?php if($preview['duplicates']):?><h3>Duplicate candidates</h3><ul><?php foreach($preview['duplicates'] as $item):?><li>Question <?= (int)$item['number']?>: <?=e($item['reason'])?></li><?php endforeach;?></ul><?php endif;?>
<?php if((int)$preview['summary']['valid']>0):?><form method="POST"><input type="hidden" name="csrf_token" value="<?=e(CSRF::getToken())?>"><button name="confirm_import" value="1" class="btn btn-primary">Import <?= (int)$preview['summary']['valid']?> Valid Records</button> <a class="btn btn-secondary" href="<?=url('admin/import.php?cancel=1')?>">Cancel</a></form><?php else:?><p class="alert alert-warning">There are no valid records to import.</p><a class="btn btn-secondary" href="<?=url('admin/import.php?cancel=1')?>">Cancel</a><?php endif;?></div>
<?php else:?><div class="card"><form method="POST" enctype="multipart/form-data"><?=CSRF::field()?><label class="form-label" for="module_id">Module</label><select class="form-control" id="module_id" name="module_id" onchange="window.location.href='<?=e(url('admin/import.php'))?>?module_id='+encodeURIComponent(this.value)" required><option value="">-- Select Module --</option><?php foreach($modules as $m):?><option value="<?= (int)$m['id']?>" <?=((int)($selectedModuleId??0)===(int)$m['id'])?'selected':''?>><?=e($m['name'])?></option><?php endforeach;?></select><label class="form-label" for="subject_id">Subject</label><select class="form-control" id="subject_id" name="subject_id" required><option value="">-- Select Subject --</option><?php foreach($subjects as $s):?><option value="<?= (int)$s['id']?>" data-module-id="<?= (int)$s['module_id']?>" <?=((int)($_POST['subject_id']??0)===(int)$s['id'])?'selected':''?>><?=e($s['name'])?></option><?php endforeach;?></select><label class="form-label" for="json_file">JSON file</label><input class="form-control" type="file" id="json_file" name="json_file" accept=".json,application/json" required><button class="btn btn-primary" type="submit">Validate and Preview</button></form></div>
<div class="card json-import-guide" style="margin-top:1.5rem;overflow-wrap:anywhere"><h2>JSON Import Guide</h2><p>Choose the Module and Subject outside the file. The top level is <code>{"questions":[...]}</code>. Never provide platform IDs.</p><h3>Common fields</h3><ul><li><code>type</code>: exactly <code>mcq</code>, <code>complete</code>, <code>match</code>, <code>compare</code>, or <code>essay</code>.</li><li><code>question</code>: non-empty text.</li><li><code>frequency</code>: integer ≥ 1; it records reported repetition and never invents appearances.</li><li><code>appearances</code>: optional array of known exam appearances. Each uses <code>source</code> (<code>final</code> or <code>end_module</code>), integer <code>year</code>, and <code>term</code> (<code>first</code> or <code>second</code>).</li><li>Omit <code>answer</code> when unavailable. Existing answers are never replaced by missing answers.</li></ul>
<h3>MCQ</h3><pre>{"type":"mcq","question":"Which vitamin is fat-soluble?","choices":{"A":"Vitamin C","B":"Vitamin D"},"answer":"B","frequency":2,"appearances":[{"source":"final","year":2025,"term":"first"}]}</pre>
<h3>Complete</h3><pre>{"type":"complete","question":"The functional unit of the kidney is the ____.","answer":"Nephron","frequency":1,"appearances":[]}</pre>
<h3>Match</h3><pre>{"type":"match","question":"Match each structure with its function.","pairs":[{"left":"A","right":"Nephron"},{"left":"B","right":"Alveolus"}],"answer":"provided","frequency":1,"appearances":[{"source":"end_module","year":2025,"term":"second"}]}</pre>
<h3>Compare</h3><pre>{"type":"compare","question":"Compare arteries and veins.","answer":"Arteries carry blood away; veins return blood.","frequency":1,"appearances":[]}</pre>
<h3>Essay</h3><pre>{"type":"essay","question":"Discuss homeostasis.","frequency":1,"appearances":[]}</pre>
<h3>True / False</h3><pre>{"type":"true_false","question":"The heart has four chambers.","answer":true,"frequency":1,"appearances":[]}</pre>
<h3>Duplicates and review</h3><p>Matching question content with a different appearance reuses one question and adds an appearance. Repeating the same appearance is skipped. MCQ identity includes normalized question text and choices. A choice/answer conflict is retained for Admin review and never silently overwrites the stored answer. Unsupported sources or terms are shown as review warnings and are not canonical filters. Legacy <code>source</code> strings are accepted only when unambiguous; the appearances array is preferred.</p></div>
<style>.json-import-guide{min-width:0;max-width:100%;box-sizing:border-box}.json-import-guide pre{white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-word;max-width:100%;box-sizing:border-box}</style>
<?php endif;?></div>
<script>const importModule=document.getElementById('module_id'),importSubject=document.getElementById('subject_id');if(importModule&&importSubject){const filter=()=>{[...importSubject.options].forEach(o=>o.hidden=o.value!==''&&o.dataset.moduleId!==importModule.value);if(importSubject.selectedOptions[0]?.hidden)importSubject.value='';};importModule.addEventListener('change',filter);filter();}</script>
