<?php
declare(strict_types=1);
define('ROOT_PATH', dirname(__DIR__));
require_once ROOT_PATH.'/config/config.php';
$passed=0;$failed=0;$ok=function(bool $v,string $n)use(&$passed,&$failed){echo($v?'[PASS] ':'[FAIL] ').$n.PHP_EOL;$v?$passed++:$failed++;};
$pdo=Database::getInstance();$pdo->exec(file_get_contents(DATABASE_PATH.'/schema.sql'));$pdo->exec('DELETE FROM quiz_answers;DELETE FROM quiz_questions;DELETE FROM quizzes;DELETE FROM question_conflicts;DELETE FROM question_sources;DELETE FROM questions;DELETE FROM subjects;DELETE FROM modules;');$pdo->exec("INSERT INTO modules(name) VALUES ('Fixture QA Module')");$m=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO subjects(module_id,name) VALUES (?,?)")->execute([$m,'Fixture QA Subject']);$s=(int)$pdo->lastInsertId();
$validFile=ROOT_PATH.'/tools/qa/manual_import_scenarios.json';$invalidFile=ROOT_PATH.'/tools/qa/manual_import_invalid_scenarios.json';$missingFile=ROOT_PATH.'/tools/qa/manual_import_invalid_missing_questions.json';$valid=json_decode(file_get_contents($validFile),true);$invalid=json_decode(file_get_contents($invalidFile),true);
$ok(is_array($valid)&&json_last_error()===JSON_ERROR_NONE&&count($valid['questions'])===33,'Valid fixture parses as 33 records');$parsed=JsonImporter::parse(file_get_contents($validFile),$m,$s);$ok($parsed['success']&&$parsed['summary']['valid']===33&&$parsed['summary']['invalid']===0,'Valid fixture preview accepts every record');$types=array_unique(array_column($parsed['valid'],'type'));$ok(count(array_intersect($types,['mcq','complete','match','compare','essay']))===5,'All five question types are accepted');$ok(count(array_filter($parsed['valid'],fn($r)=>count($r['appearances'])===0))>0&&count(array_filter($parsed['valid'],fn($r)=>count($r['appearances'])===1))>0&&count(array_filter($parsed['valid'],fn($r)=>count($r['appearances'])>1))>0,'Zero, single, and multiple appearances are covered');$ok(count(array_filter($parsed['valid'],fn($r)=>$r['answer_status']==='available'))>0&&count(array_filter($parsed['valid'],fn($r)=>$r['answer_status']==='unavailable'))>0,'Answered and unanswered records are accepted');
$import=JsonImporter::import($parsed['valid']);$ok($import['success']&&$import['new_questions']===31,'Valid fixture imports with duplicate records merged');$ok((int)$pdo->query('SELECT COUNT(*) FROM question_sources')->fetchColumn()===array_sum(array_map(fn($r)=>count($r['appearances']),$parsed['valid']))-2,'Appearance rows have no unintended duplicates');$badCount=(int)$pdo->query('SELECT COUNT(*) FROM (SELECT q.id FROM questions q LEFT JOIN question_sources qs ON qs.question_id=q.id GROUP BY q.id HAVING (COUNT(qs.id)>0 AND q.frequency<>COUNT(qs.id)) OR (COUNT(qs.id)=0 AND q.frequency<1))')->fetchColumn();$ok($badCount===0,'Imported frequencies obey appearance counts');$ok((int)$pdo->query("SELECT COUNT(*) FROM questions WHERE question_text='[QA DUPLICATE] Which nerve supplies the diaphragm?'")->fetchColumn()===1,'Duplicate identity produces one question');$ok(count(Question::getSources((int)$pdo->query("SELECT id FROM questions WHERE question_text='[QA DUPLICATE] Which nerve supplies the diaphragm?'")->fetchColumn()))===1,'Duplicate merge preserves one appearance and ignores repeat');
$before=(int)$pdo->query('SELECT COUNT(*) FROM questions')->fetchColumn();$invalidParsed=JsonImporter::parse(file_get_contents($invalidFile),$m,$s);$ok(is_array($invalid)&&count($invalid['questions'])===21&&$invalidParsed['summary']['valid']===0&&$invalidParsed['summary']['invalid']===21,'Invalid fixture rejects all 21 scenarios');$ok((int)$pdo->query('SELECT COUNT(*) FROM questions')->fetchColumn()===$before,'Invalid preview performs no inserts');$missingParsed=JsonImporter::parse(file_get_contents($missingFile),$m,$s);$ok(!$missingParsed['success']&&str_contains($missingParsed['errors'][0],'top-level'),'Missing questions structure is rejected');$ok(count($pdo->query('PRAGMA foreign_key_check')->fetchAll())===0,'Disposable database has no foreign-key violations');
$mergeParsed=JsonImporter::parse(file_get_contents(ROOT_PATH.'/tools/qa/manual_import_merge_scenarios.json'),$m,$s);$mergeImport=JsonImporter::import($mergeParsed['valid']);$dupId=(int)$pdo->query("SELECT id FROM questions WHERE question_text='[QA DUPLICATE] Which nerve supplies the diaphragm?'")->fetchColumn();$ok($mergeParsed['summary']['valid']===2&&$mergeImport['added_appearances']===1&&count(Question::getSources($dupId))===2,'Duplicate merge fixture adds one new appearance and skips the repeated appearance');
echo "Manual Import Fixture Test Results: {$passed} Passed, {$failed} Failed".PHP_EOL;exit($failed?1:0);
