<?php
declare(strict_types=1);

require_once __DIR__ . '/bootstrap.php';

$pass=0;$fail=0;$ok=function(bool $v,string $n)use(&$pass,&$fail){echo($v?'[PASS] ':'[FAIL] ').$n.PHP_EOL;$v?$pass++:$fail++;};
$pdo=Database::getInstance();$pdo->exec(file_get_contents(DATABASE_PATH.'/schema.sql'));$pdo->exec('DELETE FROM quiz_answers;DELETE FROM quiz_questions;DELETE FROM quizzes;DELETE FROM question_sources;DELETE FROM questions;DELETE FROM subjects;DELETE FROM modules;DELETE FROM users;');
$pdo->prepare("INSERT INTO users(username,password_hash,role,status) VALUES(?,?, 'student','active')")->execute(['phase6a',password_hash('pass1234',PASSWORD_DEFAULT)]);$student=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO modules(name) VALUES(?)')->execute(['Phase 6 Module']);$module=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO subjects(module_id,name) VALUES(?,?)')->execute([$module,'Phase 6 Subject']);$subject=(int)$pdo->lastInsertId();
$questions=[['mcq',['options'=>['A','B'],'correct_answer'=>'A']],['match',['left_items'=>['L1','L2'],'right_items'=>['R1','R2'],'matches'=>['L1'=>'R1','L2'=>'R2']]],['complete',['answer'=>'complete model']],['compare',['answer'=>'compare model']],['essay',['answer'=>'essay model']]];$qids=[];
foreach($questions as $i=>$item){$pdo->prepare("INSERT INTO questions(subject_id,type,question_text,answer_data,answer_status,answer_origin,frequency) VALUES(?,?,?,?, 'available','manual',?)")->execute([$subject,$item[0],"Phase 6 {$item[0]}",json_encode($item[1]),$i+1]);$qids[]=(int)$pdo->lastInsertId();}
$plan=Quiz::plan(['module_id'=>$module,'subject_ids'=>[$subject],'total_questions'=>5]);$created=Quiz::create($student,$plan);$ok($created['success'],'Generate quiz successfully');$quiz=Quiz::getForStudent($created['id'],$student);$ok($quiz!==null&&count($quiz['questions'])===5,'Take quiz successfully');
$answers=[];foreach($quiz['questions'] as $q){$data=json_decode($q['answer_data'],true);$answers[$q['quiz_question_id']]=$q['type']==='mcq'?'A':($q['type']==='match'?['L1'=>'R1','L2'=>'R2']:'student response');}
$submitted=Quiz::submit($created['id'],$student,$answers);$ok($submitted['success'],'Submit quiz successfully');$ok($submitted['score']===100.0&&$submitted['correct']===2&&$submitted['self_graded']===3,'MCQ and Match grading is correct');$ok(count($submitted['questions'])===5&&count(array_unique(array_column($submitted['questions'],'id')))===5,'Immediate result contains unique question review');
$mcqResult=array_values(array_filter($submitted['questions'],fn($q)=>$q['type']==='mcq'))[0]??null;$matchResult=array_values(array_filter($submitted['questions'],fn($q)=>$q['type']==='match'))[0]??null;$ok($mcqResult!==null&&$mcqResult['answer_data_decoded']['correct_answer']==='A'&&$mcqResult['is_correct']===1,'Immediate result displays MCQ correct answer');$ok($matchResult!==null&&$matchResult['answer_data_decoded']['matches']['L1']==='R1'&&$matchResult['is_correct']===1,'Immediate result displays Match correct mapping');
$ok((int)$pdo->query('SELECT COUNT(*) FROM quizzes')->fetchColumn()===0&&(int)$pdo->query('SELECT COUNT(*) FROM quiz_questions')->fetchColumn()===0&&(int)$pdo->query('SELECT COUNT(*) FROM quiz_answers')->fetchColumn()===0,'Submit removes the quiz and all related rows after immediate result preparation');
$schemaColumns=$pdo->query("PRAGMA table_info(quizzes)")->fetchAll(PDO::FETCH_COLUMN,1);$ok(!in_array('completed_at',$schemaColumns,true)&&!in_array('score',$schemaColumns,true),'Quiz schema has no persistent-history columns');
$ok(!file_exists(ROOT_PATH.'/public/student/quiz-history.php')&&!file_exists(ROOT_PATH.'/student/quiz-history.php')&&!file_exists(ROOT_PATH.'/tools/remove_quiz_history.php'),'Persistent quiz-history route and cleanup utility are absent');$nav=file_get_contents(ROOT_PATH.'/views/partials/nav.php');$ok(strpos($nav,'quiz-history.php')===false,'Quiz History navigation is removed');$resultController=file_get_contents(ROOT_PATH.'/public/student/quiz-result.php');$ok(strpos($resultController,"_quiz_result_payload")!==false&&strpos($resultController,'quiz-builder.php')!==false,'Result page uses immediate session payload and rejects refresh/history access');
foreach($qids as $qid){$deleted=Question::deleteQuestion($qid);$ok($deleted['success'],'Question deletion works after quiz submission');}
$subjectDelete=Academic::deleteSubject($subject);$ok($subjectDelete['success'],'Subject deletion works after completed quiz cleanup');$moduleDelete=Academic::deleteModule($module);$ok($moduleDelete['success'],'Module deletion works after completed quiz cleanup');$ok(count($pdo->query('PRAGMA foreign_key_check')->fetchAll())===0,'No foreign-key violations remain');
echo "Phase 6 Test Results: $pass Passed, $fail Failed".PHP_EOL;exit($fail?1:0);
