<div class="quiz-builder-page"><div class="page-header"><div class="page-header-info"><h1>Create Quiz</h1><p>Build a quiz from existing questions. Percentages use deterministic largest-remainder rounding.</p></div><span class="badge badge-student">Practice mode</span></div>
<?php if($errors):?><div class="alert alert-error"><?php foreach($errors as $e):?><div><?=e($e)?></div><?php endforeach;?></div><?php endif;?>
<?php if($plan):?>
<div class="card"><h2><?= $plan['exact']?'Exact quiz available':'Closest possible quiz' ?></h2><p>Requested <?= (int)$plan['requested_total'] ?> questions; proposed <?= (int)$plan['generated_total'] ?>.</p>
<?php if($plan['reasons']):?><ul><?php foreach($plan['reasons'] as $reason):?><li><?=e($reason)?></li><?php endforeach;?></ul><?php endif;?>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem"><div><h3>Question types</h3><ul><?php foreach($plan['actual_types'] as $type=>$n):?><li><?=strtoupper(e($type))?>: <?= (int)$n ?> (requested <?= (int)($plan['requested_types'][$type]??0) ?>)</li><?php endforeach;?></ul></div><div><h3>Subjects</h3><ul><?php foreach($plan['actual_subjects'] as $id=>$n):?><li><?=e($plan['subject_names'][$id]??'Selected subject')?>: <?= (int)$n ?> (requested <?= (int)($plan['requested_subjects'][$id]??0) ?>)</li><?php endforeach;?></ul></div></div>
<?php if($plan['generated_total']>0):?><form method="post"><?=CSRF::field()?><button name="create_quiz" value="1" class="btn btn-primary"><?= $plan['exact']?'Start Quiz':'Accept and Start Quiz' ?></button> <a class="btn btn-secondary" href="<?=url('student/quiz-builder.php')?>">Cancel</a></form><?php endif;?></div>
<?php else:?>
<form method="post" class="card quiz-builder-form"><?=CSRF::field()?>
<div class="form-group"><label class="form-label">Module</label><select id="module_id" name="module_id" class="form-control" required><option value="">-- Select Module --</option><?php foreach($modules as $m):?><option value="<?= (int)$m['id']?>" <?= $selectedModuleId === (int)$m['id'] ? 'selected' : '' ?>><?=e($m['name'])?></option><?php endforeach;?></select></div>
<div class="form-group"><label class="form-label">Subjects (select one or more)</label><div id="subject-list"><?php foreach($subjects as $s):?><label style="display:<?= $selectedModuleId === (int)$s['module_id'] ? 'block' : 'none' ?>;margin:.35rem 0" data-module="<?= (int)$s['module_id']?>"><input type="checkbox" name="subject_ids[]" value="<?= (int)$s['id']?>"> <?=e($s['name'])?></label><?php endforeach;?></div></div>
<div class="form-group"><label class="form-label">Total questions</label><input class="form-control" type="number" min="1" name="total_questions" required></div>
<h3 class="form-section-title">Optional question-type distribution (%)</h3><div class="distribution-grid"><?php foreach(Quiz::TYPES as $type):?><label class="distribution-field"><?=strtoupper($type)?><input class="form-control" type="number" min="0" max="100" name="type_percentages[<?=$type?>]" placeholder="%"></label><?php endforeach;?></div>
<h3 class="form-section-title">Optional subject distribution (%)</h3><p class="form-help">Leave every percentage blank to use availability.</p><div class="subject-distribution-list"><?php foreach($subjects as $s):?><label class="subject-distribution-field" style="display:<?= $selectedModuleId === (int)$s['module_id'] ? 'block' : 'none' ?>" data-subject-percent="<?= (int)$s['id']?>" data-module="<?= (int)$s['module_id']?>"><?=e($s['name'])?> <input type="number" min="0" max="100" name="subject_percentages[<?= (int)$s['id']?>]" placeholder="%"></label><?php endforeach;?></div>
<button class="btn btn-primary" style="margin-top:1.25rem">Check availability and build quiz</button></form>
<?php endif;?></div>
<script>const m=document.getElementById('module_id');if(m)m.addEventListener('change',()=>{document.querySelectorAll('[data-module]').forEach(x=>{x.style.display=x.dataset.module===m.value?'block':'none';const input=x.querySelector('input');if(x.style.display==='none'&&input){if(input.type==='checkbox')input.checked=false;else input.value='';}});});</script>
